const form=document.querySelector('#report'), status=document.querySelector('#status');
const get=()=>Object.fromEntries([...new FormData(form).entries()].map(([k,v])=>[k,v]));
function vals(){const d=get();d.under24=form.elements.under24.checked;d.under8=form.elements.under8.checked;return d}
try{const old=JSON.parse(localStorage.getItem('sertDraft')||'{}');for(const [k,v] of Object.entries(old)){let e=form.elements[k];if(e){if(e.type==='checkbox')e.checked=!!v;else e.value=v}}}catch(e){}
if(!form.elements.reportDate.value)form.elements.reportDate.value=new Date().toLocaleDateString('en-CA');
function changed(){document.querySelector('#changedWrap').classList.toggle('hidden',form.elements.changed.value!=='YES')};changed();form.elements.changed.addEventListener('change',changed);
form.addEventListener('input',()=>{localStorage.setItem('sertDraft',JSON.stringify(vals()));status.textContent='Draft saved on this device.'});
document.querySelector('#clear').onclick=()=>{if(confirm('Clear all report fields and saved draft?')){form.reset();localStorage.removeItem('sertDraft');changed();status.textContent='Report cleared.'}};
function date(v){if(!v)return '';const [y,m,d]=v.slice(0,10).split('-');return `${m}/${d}/${y}`}
function dt(v){if(!v)return '';const [ymd,hm]=v.split('T');return date(ymd)+' '+(hm||'')}
function add(cell,value){if(!cell||!value)return;let p=[...cell.getElementsByTagName('w:p')].at(-1);if(!p){p=cell.ownerDocument.createElementNS('http://schemas.openxmlformats.org/wordprocessingml/2006/main','w:p');cell.appendChild(p)}const ns='http://schemas.openxmlformats.org/wordprocessingml/2006/main';let r=cell.ownerDocument.createElementNS(ns,'w:r'),t=cell.ownerDocument.createElementNS(ns,'w:t');t.setAttribute('xml:space','preserve');t.textContent=' '+value;r.appendChild(t);p.appendChild(r)}
function cellAt(rows,r,c){return [...rows[r].getElementsByTagName('w:tc')][c]}
function replaceBox(cell,checked,index=0){if(!cell)return;let texts=[...cell.getElementsByTagName('w:t')];let hits=0;for(const t of texts){if(t.textContent.includes('☐')){t.textContent=t.textContent.replace(/☐/g,()=>{const i=hits++;return i===index&&checked?'☒':'☐'})}}}
async function build(){if(!form.reportValidity())throw new Error('Complete the required fields first.');const d=vals(),resp=await fetch('template.docx');if(!resp.ok)throw new Error('Could not load Word template');const zip=await JSZip.loadAsync(await resp.arrayBuffer());const xml=await zip.file('word/document.xml').async('string');const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw new Error('Template XML error');const tbl=doc.getElementsByTagName('w:tbl')[0],rows=[...tbl.getElementsByTagName('w:tr')];
const entries=[[0,1,d.incident],[1,1,date(d.activation)],[2,1,date(d.reportDate)],[3,0,d.member],[3,1,d.title],[4,0,d.location],[4,1,dt(d.arrival)],[5,0,dt(d.notification)],[5,1,d.workingShift],[5,2,d.supervisor],[6,0,dt(d.nextShift)],[6,1,d.changed==='YES'?dt(d.changedTime):''],[7,1,d.gapHours],[7,2,d.straight],[7,3,d.overtime],[8,0,d.summary]];
// Row cells are actual merged OOXML cells, not python-docx's expanded grid.
for(const [r,c,v] of entries)add(cellAt(rows,r,c),v);
replaceBox(cellAt(rows,6,1),d.changed==='NO',0);replaceBox(cellAt(rows,6,1),d.changed==='YES',1);
replaceBox(cellAt(rows,7,0),d.under24);replaceBox(cellAt(rows,7,1),d.under8);
zip.file('word/document.xml',new XMLSerializer().serializeToString(doc));const blob=await zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});return {blob,name:`SERT_Callout_${(d.incident||'Report').replace(/[^a-zA-Z0-9_-]/g,'_')}.docx`}}
async function exportReport(share){try{status.textContent='Generating report…';const {blob,name}=await build();const file=new File([blob],name,{type:blob.type});if(share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'SERT Callout Report'});status.textContent='Share sheet opened. Verify Outlook attachment before sending.';return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);status.textContent=share?'Saved Word file. Attach it in Outlook if the share menu is unavailable.':'Word report downloaded. Review formatting in Word.'}catch(e){status.textContent=e.message||'Export failed';if(e.name!=='AbortError')alert(status.textContent)}}
document.querySelector('#download').onclick=()=>exportReport(false);document.querySelector('#share').onclick=()=>exportReport(true);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
