const form=document.querySelector('#report'), status=document.querySelector('#status');
const get=()=>Object.fromEntries([...new FormData(form).entries()].map(([k,v])=>[k,v]));
function vals(){const d=get();d.under24=form.elements.under24.checked;d.under8=form.elements.under8.checked;return d}
const APP_VERSION='6.1.0', VAULT_KEY='sertEncryptedDraftV1';
// Non-sensitive app build history is stored separately from encrypted report data.
try{const key='sertAppVersionHistory';const hist=JSON.parse(localStorage.getItem(key)||'[]');if(hist.at(-1)?.version!==APP_VERSION){hist.push({version:APP_VERSION,installed:new Date().toISOString()});localStorage.setItem(key,JSON.stringify(hist.slice(-12)))}document.querySelector('#versionHistory').textContent='Installed versions on this device: '+hist.map(x=>x.version).join(' → ')}catch(e){}

let vaultKey=null,vaultSalt=null,saveTimer=null,saveQueue=Promise.resolve(),lastActivity=Date.now();
const vaultMessage=document.querySelector('#vaultMessage');
const enc=new TextEncoder(),dec=new TextDecoder();
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b)));
const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
function setLocked(locked){form.inert=locked;document.querySelector('#download').disabled=locked;document.querySelector('#share').disabled=locked;document.querySelector('#clear').disabled=locked;document.querySelector('#unlock').disabled=!locked;document.querySelector('#vaultPass').disabled=!locked;document.querySelector('#lock').disabled=locked;status.textContent=locked?'Encrypted vault locked.':'Encrypted vault unlocked. Drafts save on this device.';}
function changed(){document.querySelector('#changedWrap').classList.toggle('hidden',form.elements.changed.value!=='YES')};changed();form.elements.changed.addEventListener('change',changed);
async function derive(pass,salt){const base=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptDraft(data){const iv=crypto.getRandomValues(new Uint8Array(12));const ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},vaultKey,enc.encode(JSON.stringify(data)));return JSON.stringify({format:1,salt:b64(vaultSalt),iv:b64(iv),data:b64(ct)})}
async function decryptDraft(record,key){const pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(record.iv)},key,unb64(record.data));return JSON.parse(dec.decode(pt))}
function fill(d){for(const [k,v] of Object.entries(d)){let e=form.elements[k];if(e){if(e.type==='checkbox')e.checked=!!v;else e.value=v}}changed()}
async function persist(){if(!vaultKey)return;const data=vals(),key=vaultKey,salt=vaultSalt;saveQueue=saveQueue.then(async()=>{if(vaultKey!==key)return;const payload=await encryptDraft(data);if(vaultKey===key)localStorage.setItem(VAULT_KEY,payload)}).catch(e=>{status.textContent='Encrypted save failed: '+e.message});await saveQueue;status.textContent='Encrypted draft saved on this device.'}
function scheduleSave(){if(!vaultKey)return;clearTimeout(saveTimer);saveTimer=setTimeout(()=>{persist()},450)}
form.addEventListener('input',()=>{lastActivity=Date.now();scheduleSave()});form.addEventListener('change',()=>{lastActivity=Date.now();scheduleSave()});
async function lockVault(){clearTimeout(saveTimer);if(vaultKey)await persist();vaultKey=null;vaultSalt=null;form.reset();changed();document.querySelector('#vaultPass').value='';setLocked(true);vaultMessage.textContent='Locked. Enter your passphrase to unlock.'}
document.querySelector('#unlock').onclick=async()=>{const pass=document.querySelector('#vaultPass').value;if(pass.length<12){vaultMessage.textContent='Use a passphrase of at least 12 characters.';return}try{const stored=localStorage.getItem(VAULT_KEY),record=stored?JSON.parse(stored):null;const salt=record?unb64(record.salt):crypto.getRandomValues(new Uint8Array(16));const key=await derive(pass,salt);const data=record?await decryptDraft(record,key):{};vaultKey=key;vaultSalt=salt;fill(data);if(!form.elements.reportDate.value){const now=new Date();form.elements.reportDate.value=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;}setLocked(false);document.querySelector('#vaultPass').value='';lastActivity=Date.now();vaultMessage.textContent=record?'Draft decrypted.':'New encrypted vault created.';if(!record){const legacy=localStorage.getItem('sertDraft');if(legacy){if(confirm('An older unencrypted draft exists. Import it into your encrypted vault?')){try{fill(JSON.parse(legacy))}catch(e){} }localStorage.removeItem('sertDraft')}await persist()}}catch(e){vaultMessage.textContent='Could not unlock. Check passphrase, or the encrypted data may be damaged.';vaultKey=null;vaultSalt=null;setLocked(true)}};
document.querySelector('#lock').onclick=lockVault;
setLocked(true);
// Inactivity check is best-effort: iOS may suspend background timers.
setInterval(()=>{if(vaultKey&&Date.now()-lastActivity>5*60*1000)lockVault()},30000);
document.addEventListener('visibilitychange',()=>{if(document.hidden&&vaultKey){clearTimeout(saveTimer);persist()}});
document.querySelector('#clear').onclick=async()=>{if(confirm('Clear all report fields and encrypted saved draft?')){clearTimeout(saveTimer);form.reset();changed();await persist();status.textContent='Report cleared; empty draft encrypted.'}};
function date(v){if(!v)return '';const [y,m,d]=v.slice(0,10).split('-');return `${m}/${d}/${y}`}
function dt(v){if(!v)return '';const [ymd,hm]=v.split('T');return date(ymd)+' '+(hm||'').slice(0,5)}
function add(cell,value){if(!cell||!value)return;let p=[...cell.getElementsByTagName('w:p')].at(-1);if(!p){p=cell.ownerDocument.createElementNS('http://schemas.openxmlformats.org/wordprocessingml/2006/main','w:p');cell.appendChild(p)}const ns='http://schemas.openxmlformats.org/wordprocessingml/2006/main';let r=cell.ownerDocument.createElementNS(ns,'w:r'),t=cell.ownerDocument.createElementNS(ns,'w:t');t.setAttribute('xml:space','preserve');t.textContent=' '+value;r.appendChild(t);p.appendChild(r)}
function cellAt(rows,r,c){return [...rows[r].getElementsByTagName('w:tc')][c]}
function replaceBox(cell,checked,index=0){if(!cell)return;let texts=[...cell.getElementsByTagName('w:t')];let hits=0;for(const t of texts){if(t.textContent.includes('☐')){t.textContent=t.textContent.replace(/☐/g,()=>{const i=hits++;return i===index&&checked?'☒':'☐'})}}}
async function build(){if(!form.reportValidity())throw new Error('Complete the required fields first.');const d=vals();if(d.summary.length>1100&&!confirm('Long summary may require more than one page. Continue?'))throw new Error('Export cancelled.');const resp=await fetch('template.docx');if(!resp.ok)throw new Error('Could not load Word template');const zip=await JSZip.loadAsync(await resp.arrayBuffer());const xml=await zip.file('word/document.xml').async('string');const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw new Error('Template XML error');const tbl=doc.getElementsByTagName('w:tbl')[0],rows=[...tbl.getElementsByTagName('w:tr')];
const entries=[[0,1,d.incident],[1,1,date(d.activation)],[2,1,date(d.reportDate)],[3,0,d.member],[3,1,d.title],[4,0,d.location],[4,1,dt(d.arrival)],[5,0,dt(d.notification)],[5,1,d.workingShift],[5,2,d.supervisor],[6,0,dt(d.nextShift)],[6,1,d.changed==='YES'?dt(d.changedTime):''],[7,1,d.gapHours],[7,2,d.straight],[7,3,d.overtime],[8,0,d.summary]];
// Row cells are actual merged OOXML cells, not python-docx's expanded grid.
for(const [r,c,v] of entries)add(cellAt(rows,r,c),v);
replaceBox(cellAt(rows,6,1),d.changed==='NO',0);replaceBox(cellAt(rows,6,1),d.changed==='YES',1);
replaceBox(cellAt(rows,7,0),d.under24);replaceBox(cellAt(rows,7,1),d.under8);
zip.file('word/document.xml',new XMLSerializer().serializeToString(doc));const blob=await zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});return {blob,name:`SERT_Callout_${(d.incident||'Report').replace(/[^a-zA-Z0-9_-]/g,'_')}.docx`}}
async function exportReport(share){try{if(!vaultKey)throw new Error('Unlock the encrypted vault first.');status.textContent='Generating report…';const {blob,name}=await build();const file=new File([blob],name,{type:blob.type});if(share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'SERT Callout Report'});status.textContent='Share sheet opened. Verify Outlook attachment before sending.';return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);status.textContent=share?'Saved Word file. Attach it in Outlook if the share menu is unavailable.':'Word report downloaded. Review formatting in Word.'}catch(e){status.textContent=e.message||'Export failed';if(e.name!=='AbortError')alert(status.textContent)}}
document.querySelector('#download').onclick=()=>exportReport(false);document.querySelector('#share').onclick=()=>exportReport(true);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
